### ISSUE TITLE
Servidor do Jean

### ISSUE THREAD

**Issue by neninja** [StopProject/stopProject#1]
Pode me confirmar o endereço do servidor para consumir a api?
Atualmente possuo anotado: ``http://149.56.133.212:8081/StopWeb/getPartida``, porém está dando erro.
Há algum outro?

![image](https://user-images.githubusercontent.com/29121828/42096915-049e0826-7b8d-11e8-9346-a4d20b7387ea.png)

**Comment by jeanpaullopes** [comment]
Verificando. provavelmente o serviço não estão "levantado".

**Comment by jeanpaullopes** [comment]
Já no ar.
Por que está usando o endPoint de ajax?

**Comment by neninja** [comment]
Olá Jean, agora foi, tudo certo. Eu tava me referindo a somente o ip ``149.56.133.212:8081``, pois estou criando a instancia do ws com a seguinte linha:
```javascript
this.websocket = new WebSocket('ws://149.56.133.212:8081/StopWeb/websocket?nome=' + nome);
```
Muito obrigado por responder em pouco tempo, vou poder passar o fds codando.
